import express from "express";
import path from "path";
import { createServer as createViteServer } from "vite";
import { GoogleGenAI, Type } from "@google/genai";
import dotenv from "dotenv";

dotenv.config();

const app = express();
const PORT = 3000;

app.use(express.json({ limit: "10mb" }));

// Lazy initializer for Gemini to prevent startup crashes if key is omitted or during first run
let aiClient: GoogleGenAI | null = null;
function getGeminiClient(): GoogleGenAI | null {
  if (!aiClient) {
    const apiKey = process.env.GEMINI_API_KEY;
    if (apiKey && apiKey !== "MY_GEMINI_API_KEY") {
      aiClient = new GoogleGenAI({
        apiKey: apiKey,
        httpOptions: {
          headers: {
            "User-Agent": "aistudio-build",
          },
        },
      });
    }
  }
  return aiClient;
}

// REST route for our Cloud Brain LLM agent simulation
app.post("/api/agent/prompt", async (req, res) => {
  const { prompt, files, history } = req.body;

  try {
    const ai = getGeminiClient();
    if (!ai) {
      // In case there is no API key configured, we provide a sophisticated local rules-based simulation response.
      // This ensures the application is 100% useful, elegant, and interactive right away!
      const simulatedPlan = generateFallbackPlan(prompt, files);
      return res.json({
        success: true,
        isSimulated: true,
        plan: simulatedPlan,
        rawResponse: "Simulated response generated by local procedural brain (No Gemini API Key found in .env)."
      });
    }

    // Prepare full current files state and prompt for Gemini
    const systemInstruction = `You are the ultimate enterprise-grade Cloud Brain Developer Agent.
Your job is to receive a natural language request and the current virtual project files, then generate a highly structured step-by-step developer implementation plan.
You must return only a JSON array matching the specified schema.

Your plans consist of discrete steps. Available steps:
1. {"action": "thought", "text": "A detailed explanation of what you are planning to do."}
2. {"action": "write_file", "path": "filename", "content": "The complete source code of the file."}
3. {"action": "read_file", "path": "filename"}
4. {"action": "execute_shell", "command": "npm install/build/test etc."}

Example Output Scheme:
[
  { "action": "thought", "text": "Let's first create the entry point file for the new landing page." },
  { "action": "write_file", "path": "src/Home.tsx", "content": "import React from 'react';\\nexport default function Home() { ... }" },
  { "action": "execute_shell", "command": "npm run build" }
]

Keep plans concise: between 2 to 5 steps maximum. Make sure the files you generate are complete and clean. 
Always output VALID JSON as a direct array (no markdown code blocks, just raw JSON).`;

    const formattedWorkspace = Object.entries(files || {})
      .map(([path, content]) => `--- File: ${path} ---\n${content}`)
      .join("\n\n");

    const promptMessage = `USER REQUEST: "${prompt}"

CURRENT WORKSPACE FILES:
${formattedWorkspace}

Please generate the optimal developer execution plan for this request.`;

    const response = await ai.models.generateContent({
      model: "gemini-3.5-flash",
      contents: promptMessage,
      config: {
        systemInstruction,
        responseMimeType: "application/json",
        responseSchema: {
          type: Type.ARRAY,
          items: {
            type: Type.OBJECT,
            properties: {
              action: {
                type: Type.STRING,
                description: "The type of action: thought, write_file, read_file, execute_shell",
              },
              text: {
                type: Type.STRING,
                description: "The thought process explanation (required for 'thought' action)",
              },
              path: {
                type: Type.STRING,
                description: "The target file path (required for 'write_file' or 'read_file' action)",
              },
              content: {
                type: Type.STRING,
                description: "The complete content to write into the file (required for 'write_file' action)",
              },
              command: {
                type: Type.STRING,
                description: "The shell command to execute (required for 'execute_shell' action)",
              },
            },
            required: ["action"],
          },
        },
      },
    });

    const text = response.text || "[]";
    const parsedPlan = JSON.parse(text.trim());

    res.json({
      success: true,
      isSimulated: false,
      plan: parsedPlan,
      rawResponse: text,
    });
  } catch (err: any) {
    console.error("Gemini API Error:", err);
    res.status(500).json({
      success: false,
      error: err.message || "An error occurred while generating agent plan",
    });
  }
});

// Helper for high-fidelity fallback plans when API key is missing
function generateFallbackPlan(prompt: string, files: any) {
  const query = prompt.toLowerCase();
  
  if (query.includes("weather") || query.includes("temperature")) {
    return [
      {
        action: "thought",
        text: "Analyzing user request for a weather widget. I need to construct a modern weather forecasting card with detailed metrics and beautiful visual states."
      },
      {
        action: "write_file",
        path: "src/weather.js",
        content: `// Simulated Location Weather API Adapter
export const WEATHER_DATA = {
  city: "San Francisco",
  temp: "19°C",
  condition: "Partly Cloudy",
  humidity: "62%",
  wind: "14 km/h",
  forecast: [
    { day: "Mon", temp: "18°C", cond: "sunny" },
    { day: "Tue", temp: "20°C", cond: "sunny" },
    { day: "Wed", temp: "16°C", cond: "cloud" },
    { day: "Thu", temp: "19°C", cond: "cloud" },
    { day: "Fri", temp: "21°C", cond: "sunny" }
  ]
};`
      },
      {
        action: "write_file",
        path: "index.html",
        content: `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdn.tailwindcss.com"></script>
    <title>Sleek Weather Card</title>
</head>
<body class="bg-slate-900 text-white min-h-screen flex items-center justify-center p-6">
    <div class="max-w-md w-full bg-slate-800/80 backdrop-blur border border-slate-700 rounded-3xl p-6 shadow-2xl relative overflow-hidden">
        <!-- Accent Glow -->
        <div class="absolute -right-16 -top-16 w-36 h-36 bg-cyan-500/20 rounded-full blur-3xl"></div>
        
        <div class="flex justify-between items-start mb-6">
            <div>
                <h1 class="text-2xl font-bold tracking-tight">San Francisco</h1>
                <p class="text-sm text-slate-400">California, USA</p>
            </div>
            <div class="text-xs bg-cyan-500/10 text-cyan-400 px-2.5 py-1 rounded-full font-mono">Live Sync</div>
        </div>

        <div class="flex items-center justify-between my-8">
            <div class="text-5xl font-extrabold tracking-tighter text-transparent bg-clip-text bg-gradient-to-r from-white to-slate-300">19°C</div>
            <div class="text-right">
                <p class="text-lg font-semibold text-cyan-300">Partly Cloudy</p>
                <p class="text-xs text-slate-400">Feels like 17°C</p>
            </div>
        </div>

        <div class="grid grid-cols-2 gap-4 bg-slate-950/40 p-4 rounded-2xl border border-slate-700/50 mb-6">
            <div>
                <p class="text-[10px] text-slate-500 uppercase font-mono">Humidity</p>
                <p class="text-sm font-semibold">62%</p>
            </div>
            <div>
                <p class="text-[10px] text-slate-500 uppercase font-mono">Wind speed</p>
                <p class="text-sm font-semibold">14 km/h</p>
            </div>
        </div>

        <div class="pt-4 border-t border-slate-700/60">
            <p class="text-xs text-slate-400 mb-3 font-semibold">5-Day Forecast</p>
            <div class="flex justify-between text-xs">
                <div class="text-center"><p class="text-slate-500">Mon</p><p class="font-bold">18°</p></div>
                <div class="text-center"><p class="text-slate-500">Tue</p><p class="font-bold text-yellow-400">20°</p></div>
                <div class="text-center"><p class="text-slate-500">Wed</p><p class="font-bold">16°</p></div>
                <div class="text-center"><p class="text-slate-500">Thu</p><p class="font-bold">19°</p></div>
                <div class="text-center"><p class="text-slate-500">Fri</p><p class="font-bold text-yellow-400">21°</p></div>
            </div>
        </div>
    </div>
</body>
</html>`
      },
      {
        action: "execute_shell",
        command: "npm run build"
      }
    ];
  } else if (query.includes("todo") || query.includes("task")) {
    return [
      {
        action: "thought",
        text: "Building an immersive local Task Organizer applet featuring persistent states and custom progress meters."
      },
      {
        action: "write_file",
        path: "index.html",
        content: `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdn.tailwindcss.com"></script>
    <title>Quantum Tasks</title>
</head>
<body class="bg-indigo-950 min-h-screen flex items-center justify-center p-6 text-white font-sans">
    <div class="w-full max-w-md bg-slate-900 border border-slate-800 rounded-2xl shadow-xl overflow-hidden">
        <div class="p-6 bg-gradient-to-b from-indigo-500/10 to-transparent">
            <h1 class="text-xl font-bold tracking-tight">Quantum Tasks</h1>
            <p class="text-xs text-slate-400">Simulated secure agentic todo applet</p>
        </div>
        <div class="px-6 pb-6 space-y-3">
            <div class="flex items-center space-x-3 p-3 bg-slate-800/40 rounded-xl border border-slate-700/50">
                <input type="checkbox" checked class="w-4 h-4 rounded text-indigo-500">
                <span class="text-sm line-through text-slate-500">Enable local safety protocol sandbox</span>
            </div>
            <div class="flex items-center space-x-3 p-3 bg-slate-800/40 rounded-xl border border-slate-700/50">
                <input type="checkbox" checked class="w-4 h-4 rounded text-indigo-500">
                <span class="text-sm line-through text-slate-500">Implement exponential backoff logic</span>
            </div>
            <div class="flex items-center space-x-3 p-3 bg-slate-800/40 rounded-xl border border-slate-700/50">
                <input type="checkbox" class="w-4 h-4 rounded text-indigo-500">
                <span class="text-sm text-slate-300">Set up multi-region failover cluster</span>
            </div>
            
            <div class="mt-6 flex space-x-2 pt-4">
                <input type="text" placeholder="Add quantum task..." class="flex-1 bg-slate-950 border border-slate-800 text-xs rounded-lg px-3 py-2 text-white outline-none focus:border-indigo-500">
                <button class="bg-indigo-600 hover:bg-indigo-500 text-xs font-bold px-4 py-2 rounded-lg transition">Add</button>
            </div>
        </div>
    </div>
</body>
</html>`
      },
      {
        action: "execute_shell",
        command: "npm run test"
      }
    ];
  } else {
    // Default smart mock response
    return [
      {
        action: "thought",
        text: `Executing custom plan for prompt: "${prompt}". Let's create an elegant, single-page presentation layout containing the user's customized component design.`
      },
      {
        action: "write_file",
        path: "index.html",
        content: `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdn.tailwindcss.com"></script>
    <title>${prompt}</title>
</head>
<body class="bg-zinc-950 text-slate-100 min-h-screen flex flex-col items-center justify-center p-8">
    <div class="max-w-xl w-full text-center space-y-6">
        <div class="inline-block p-2.5 bg-violet-500/10 text-violet-400 rounded-2xl border border-violet-500/20 text-xs font-mono mb-2">
            Cloud Brain Generated Result
        </div>
        <h1 class="text-4xl font-extrabold tracking-tight sm:text-5xl text-transparent bg-clip-text bg-gradient-to-r from-violet-400 via-fuchsia-300 to-cyan-400">
            ${prompt}
        </h1>
        <p class="text-base text-slate-400 max-w-md mx-auto leading-relaxed">
            This module was designed in the Cloud Brain and safely compiled inside the Local Bouncer Executor using secure pipeline rules.
        </p>
        
        <div class="bg-slate-900 border border-slate-800 rounded-2xl p-5 text-left font-mono text-xs text-emerald-400 space-y-2 max-w-sm mx-auto shadow-xl">
            <div class="flex items-center space-x-2">
                <span class="w-2.5 h-2.5 rounded-full bg-emerald-500 animate-pulse"></span>
                <span>Compile success! 0 errors</span>
            </div>
            <p class="text-slate-500">Completed at: ${new Date().toLocaleTimeString()}</p>
        </div>
    </div>
</body>
</html>`
      },
      {
        action: "execute_shell",
        command: "npm run build"
      }
    ];
  }
}

async function startServer() {
  if (process.env.NODE_ENV !== "production") {
    // Vite middleware for lightning-fast HMR and bundling on development
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.use(vite.middlewares);
  } else {
    // Production serving static assets
    const distPath = path.join(process.cwd(), "dist");
    app.use(express.static(distPath));
    app.get("*", (req, res) => {
      res.sendFile(path.join(distPath, "index.html"));
    });
  }

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`Cloud-Brain / Agent Sandbox Server listening on port ${PORT}`);
  });
}

startServer();
